// Product data organized by series/category
// Each product has a mainCategory for navigation filtering
export const PRODUCTS = [
  // ========== ELFBAR Moonlight 40K Series ==========
  {
    id: "elfbar-moonlight-40k-blackberry-ice",
    brand: "ELFBAR",
    series: "Moonlight 40K",
    category: "elfbar-moonlight-40k",
    mainCategory: "disposable",
    flavor: "Blackberry Ice",
    type: "Rechargeable Disposable",
    puffs: 40000,
    nicotine: "5%",
    features: "3-Level Adjustable Power",
    price: 1799,
    originalPrice: null,
    soldOut: false,
    isBestSelling: true,
    poster: "/images/products/elfbar-moonlight-40k/blackberry-ice.png",
    cardImage: "/images/products/elfbar-moonlight-40k/blackberry-ice.png",
    modelUrl: ""
  },
  {
    id: "elfbar-moonlight-40k-kiwi-passion-guava",
    brand: "ELFBAR",
    series: "Moonlight 40K",
    category: "elfbar-moonlight-40k",
    mainCategory: "disposable",
    flavor: "Kiwi Passion Fruit Guava",
    type: "Rechargeable Disposable",
    puffs: 40000,
    nicotine: "5%",
    features: "3-Level Adjustable Power",
    price: 1799,
    originalPrice: null,
    soldOut: false,
    isBestSelling: false,
    poster: "/images/products/elfbar-moonlight-40k/kiwi-passion-guava.png",
    cardImage: "/images/products/elfbar-moonlight-40k/kiwi-passion-guava.png",
    modelUrl: ""
  },
  {
    id: "elfbar-moonlight-40k-triple-mango",
    brand: "ELFBAR",
    series: "Moonlight 40K",
    category: "elfbar-moonlight-40k",
    mainCategory: "disposable",
    flavor: "Triple Mango",
    type: "Rechargeable Disposable",
    puffs: 40000,
    nicotine: "5%",
    features: "3-Level Adjustable Power",
    price: 1799,
    originalPrice: null,
    soldOut: false,
    isBestSelling: true,
    poster: "/images/products/elfbar-moonlight-40k/triple-mango.png",
    cardImage: "/images/products/elfbar-moonlight-40k/triple-mango.png",
    modelUrl: ""
  },
  {
    id: "elfbar-moonlight-40k-blueberry-raspberry-watermelon",
    brand: "ELFBAR",
    series: "Moonlight 40K",
    category: "elfbar-moonlight-40k",
    mainCategory: "disposable",
    flavor: "Blueberry Raspberry Watermelon",
    type: "Rechargeable Disposable",
    puffs: 40000,
    nicotine: "5%",
    features: "3-Level Adjustable Power",
    price: 1799,
    originalPrice: null,
    soldOut: false,
    isBestSelling: false,
    poster: "/images/products/elfbar-moonlight-40k/blueberry-raspberry-watermelon.png",
    cardImage: "/images/products/elfbar-moonlight-40k/blueberry-raspberry-watermelon.png",
    modelUrl: ""
  },
  {
    id: "elfbar-moonlight-40k-strawberry-watermelon",
    brand: "ELFBAR",
    series: "Moonlight 40K",
    category: "elfbar-moonlight-40k",
    mainCategory: "disposable",
    flavor: "Strawberry Watermelon",
    type: "Rechargeable Disposable",
    puffs: 40000,
    nicotine: "5%",
    features: "3-Level Adjustable Power",
    price: 1799,
    originalPrice: null,
    soldOut: false,
    isBestSelling: false,
    poster: "/images/products/elfbar-moonlight-40k/strawberry-watermelon.png",
    cardImage: "/images/products/elfbar-moonlight-40k/strawberry-watermelon.png",
    modelUrl: ""
  },
  {
    id: "elfbar-moonlight-40k-grape-ice",
    brand: "ELFBAR",
    series: "Moonlight 40K",
    category: "elfbar-moonlight-40k",
    mainCategory: "disposable",
    flavor: "Grape Ice",
    type: "Rechargeable Disposable",
    puffs: 40000,
    nicotine: "5%",
    features: "3-Level Adjustable Power",
    price: 1799,
    originalPrice: null,
    soldOut: false,
    isBestSelling: true,
    poster: "/images/products/elfbar-moonlight-40k/grape-ice.png",
    cardImage: "/images/products/elfbar-moonlight-40k/grape-ice.png",
    modelUrl: ""
  },
  {
    id: "elfbar-moonlight-40k-strawberry-kiwi-ice",
    brand: "ELFBAR",
    series: "Moonlight 40K",
    category: "elfbar-moonlight-40k",
    mainCategory: "disposable",
    flavor: "Strawberry Kiwi Ice",
    type: "Rechargeable Disposable",
    puffs: 40000,
    nicotine: "5%",
    features: "3-Level Adjustable Power",
    price: 1799,
    originalPrice: null,
    soldOut: false,
    isBestSelling: false,
    poster: "/images/products/elfbar-moonlight-40k/strawberry-kiwi-ice.png",
    cardImage: "/images/products/elfbar-moonlight-40k/strawberry-kiwi-ice.png",
    modelUrl: ""
  },
  {
    id: "elfbar-moonlight-40k-blackberry-cranberry",
    brand: "ELFBAR",
    series: "Moonlight 40K",
    category: "elfbar-moonlight-40k",
    mainCategory: "disposable",
    flavor: "Blackberry Cranberry",
    type: "Rechargeable Disposable",
    puffs: 40000,
    nicotine: "5%",
    features: "3-Level Adjustable Power",
    price: 1799,
    originalPrice: null,
    soldOut: false,
    isBestSelling: false,
    poster: "/images/products/elfbar-moonlight-40k/blackberry-cranberry.png",
    cardImage: "/images/products/elfbar-moonlight-40k/blackberry-cranberry.png",
    modelUrl: ""
  },
  {
    id: "elfbar-moonlight-40k-blueberry-ice",
    brand: "ELFBAR",
    series: "Moonlight 40K",
    category: "elfbar-moonlight-40k",
    mainCategory: "disposable",
    flavor: "Blueberry Ice",
    type: "Rechargeable Disposable",
    puffs: 40000,
    nicotine: "5%",
    features: "3-Level Adjustable Power",
    price: 1799,
    originalPrice: null,
    soldOut: false,
    isBestSelling: false,
    poster: "/images/products/elfbar-moonlight-40k/blueberry-ice.png",
    cardImage: "/images/products/elfbar-moonlight-40k/blueberry-ice.png",
    modelUrl: ""
  },
  {
    id: "elfbar-moonlight-40k-cola-ice",
    brand: "ELFBAR",
    series: "Moonlight 40K",
    category: "elfbar-moonlight-40k",
    mainCategory: "disposable",
    flavor: "Cola Ice",
    type: "Rechargeable Disposable",
    puffs: 40000,
    nicotine: "5%",
    features: "3-Level Adjustable Power",
    price: 1799,
    originalPrice: null,
    soldOut: false,
    isBestSelling: false,
    poster: "/images/products/elfbar-moonlight-40k/cola-ice.png",
    cardImage: "/images/products/elfbar-moonlight-40k/cola-ice.png",
    modelUrl: ""
  },

  // ========== ELFBAR Sweet King Series ==========
  ...Array(5).fill(null).map((_, i) => ({
    id: `elfbar-sweet-king-${['kiwi-passion-guava', 'cotton-candy-ice', 'strawberry-mango', 'grape-honeydew', 'triple-melon'][i]}`,
    brand: "ELFBAR",
    series: "Sweet King",
    category: "elfbar-sweet-king",
    mainCategory: "disposable",
    flavor: ['Kiwi Passion Fruit Guava', 'Cotton Candy Ice', 'Strawberry Mango', 'Grape Honeydew', 'Triple Melon'][i],
    type: "Rechargeable Disposable",
    puffs: 15000,
    nicotine: "5%",
    features: "4 Levels Personalized Sweetness",
    price: 1399,
    originalPrice: null,
    soldOut: false,
    isBestSelling: i === 0 || i === 2,
    poster: `/images/products/elfbar-sweet-king/${['kiwi-passion-guava', 'cotton-candy-ice', 'strawberry-mango', 'grape-honeydew', 'triple-melon'][i]}.png`,
    cardImage: `/images/products/elfbar-sweet-king/${['kiwi-passion-guava', 'cotton-candy-ice', 'strawberry-mango', 'grape-honeydew', 'triple-melon'][i]}.png`,
    modelUrl: ""
  })),

  // ========== ELFBAR Raya D3 Series ==========
  {
    id: "elfbar-raya-d3-pineapple-kiwi-ice",
    brand: "ELFBAR",
    series: "Raya D3",
    category: "elfbar-raya-d3",
    mainCategory: "disposable",
    flavor: "Pineapple Kiwi Ice",
    type: "Disposable Pod Device",
    puffs: 25000,
    nicotine: "50mg/ml",
    features: "1st Triple Mesh Coil | 3 Modes (Lite, Smooth, Turbo)",
    price: 1599,
    originalPrice: null,
    soldOut: false,
    isBestSelling: false,
    poster: "/images/products/elfbar-raya-d3/pineapple-kiwi-ice.png",
    cardImage: "/images/products/elfbar-raya-d3/pineapple-kiwi-ice.png",
    modelUrl: ""
  },
  {
    id: "elfbar-raya-d3-kiwi-passion-guava",
    brand: "ELFBAR",
    series: "Raya D3",
    category: "elfbar-raya-d3",
    mainCategory: "disposable",
    flavor: "Kiwi Passion Fruit Guava",
    type: "Disposable Pod Device",
    puffs: 25000,
    nicotine: "50mg/ml",
    features: "1st Triple Mesh Coil | 3 Modes (Lite, Smooth, Turbo)",
    price: 1599,
    originalPrice: null,
    soldOut: false,
    isBestSelling: false,
    poster: "/images/products/elfbar-raya-d3/kiwi-passion-guava.png",
    cardImage: "/images/products/elfbar-raya-d3/kiwi-passion-guava.png",
    modelUrl: ""
  },
  {
    id: "elfbar-raya-d3-apple-peach",
    brand: "ELFBAR",
    series: "Raya D3",
    category: "elfbar-raya-d3",
    mainCategory: "disposable",
    flavor: "Apple Peach",
    type: "Disposable Pod Device",
    puffs: 25000,
    nicotine: "50mg/ml",
    features: "1st Triple Mesh Coil | 3 Modes (Lite, Smooth, Turbo)",
    price: 1599,
    originalPrice: null,
    soldOut: false,
    isBestSelling: true,
    poster: "/images/products/elfbar-raya-d3/apple-peach.png",
    cardImage: "/images/products/elfbar-raya-d3/apple-peach.png",
    modelUrl: ""
  },
  {
    id: "elfbar-raya-d3-strawberry-raspberry-cherry",
    brand: "ELFBAR",
    series: "Raya D3",
    category: "elfbar-raya-d3",
    mainCategory: "disposable",
    flavor: "Strawberry Raspberry Cherry",
    type: "Disposable Pod Device",
    puffs: 25000,
    nicotine: "50mg/ml",
    features: "1st Triple Mesh Coil | 3 Modes (Lite, Smooth, Turbo)",
    price: 1599,
    originalPrice: null,
    soldOut: false,
    isBestSelling: false,
    poster: "/images/products/elfbar-raya-d3/strawberry-raspberry-cherry.png",
    cardImage: "/images/products/elfbar-raya-d3/strawberry-raspberry-cherry.png",
    modelUrl: ""
  },
  {
    id: "elfbar-raya-d3-grape-ice",
    brand: "ELFBAR",
    series: "Raya D3",
    category: "elfbar-raya-d3",
    mainCategory: "disposable",
    flavor: "Grape Ice",
    type: "Disposable Pod Device",
    puffs: 25000,
    nicotine: "50mg/ml",
    features: "1st Triple Mesh Coil | 3 Modes (Lite, Smooth, Turbo)",
    price: 1599,
    originalPrice: null,
    soldOut: false,
    isBestSelling: true,
    poster: "/images/products/elfbar-raya-d3/grape-ice.png",
    cardImage: "/images/products/elfbar-raya-d3/grape-ice.png",
    modelUrl: ""
  },
  {
    id: "elfbar-raya-d3-double-apple",
    brand: "ELFBAR",
    series: "Raya D3",
    category: "elfbar-raya-d3",
    mainCategory: "disposable",
    flavor: "Double Apple",
    type: "Disposable Pod Device",
    puffs: 25000,
    nicotine: "50mg/ml",
    features: "1st Triple Mesh Coil | 3 Modes (Lite, Smooth, Turbo)",
    price: 1599,
    originalPrice: null,
    soldOut: false,
    isBestSelling: false,
    poster: "/images/products/elfbar-raya-d3/double-apple.png",
    cardImage: "/images/products/elfbar-raya-d3/double-apple.png",
    modelUrl: ""
  },
  {
    id: "elfbar-raya-d3-pineapple-mango-ice",
    brand: "ELFBAR",
    series: "Raya D3",
    category: "elfbar-raya-d3",
    mainCategory: "disposable",
    flavor: "Pineapple Mango Ice",
    type: "Disposable Pod Device",
    puffs: 25000,
    nicotine: "50mg/ml",
    features: "1st Triple Mesh Coil | 3 Modes (Lite, Smooth, Turbo)",
    price: 1599,
    originalPrice: null,
    soldOut: false,
    isBestSelling: false,
    poster: "/images/products/elfbar-raya-d3/pineapple-mango-ice.png",
    cardImage: "/images/products/elfbar-raya-d3/pineapple-mango-ice.png",
    modelUrl: ""
  },
  {
    id: "elfbar-raya-d3-apple-shisha",
    brand: "ELFBAR",
    series: "Raya D3",
    category: "elfbar-raya-d3",
    mainCategory: "disposable",
    flavor: "Apple Shisha",
    type: "Disposable Pod Device",
    puffs: 25000,
    nicotine: "50mg/ml",
    features: "1st Triple Mesh Coil | 3 Modes (Lite, Smooth, Turbo)",
    price: 1599,
    originalPrice: null,
    soldOut: false,
    isBestSelling: false,
    poster: "/images/products/elfbar-raya-d3/apple-shisha.png",
    cardImage: "/images/products/elfbar-raya-d3/apple-shisha.png",
    modelUrl: ""
  },
  {
    id: "elfbar-raya-d3-grape-mint",
    brand: "ELFBAR",
    series: "Raya D3",
    category: "elfbar-raya-d3",
    mainCategory: "disposable",
    flavor: "Grape Mint",
    type: "Disposable Pod Device",
    puffs: 25000,
    nicotine: "50mg/ml",
    features: "1st Triple Mesh Coil | 3 Modes (Lite, Smooth, Turbo)",
    price: 1599,
    originalPrice: null,
    soldOut: false,
    isBestSelling: false,
    poster: "/images/products/elfbar-raya-d3/grape-mint.png",
    cardImage: "/images/products/elfbar-raya-d3/grape-mint.png",
    modelUrl: ""
  },

  // ========== ELFBAR Raya D1 Series ==========
  {
    id: "elfbar-raya-d1-pink-peach",
    brand: "ELFBAR",
    series: "Raya D1",
    category: "elfbar-raya-d1",
    mainCategory: "disposable",
    flavor: "Pink Peach",
    type: "Disposable Pod Device",
    puffs: 12000,
    nicotine: "50mg/ml",
    features: "E-Liquid Display | Power Display | Sunit Edition",
    price: 1199,
    originalPrice: null,
    soldOut: false,
    isBestSelling: false,
    poster: "/images/products/elfbar-raya-d1/pink-peach.png",
    cardImage: "/images/products/elfbar-raya-d1/pink-peach.png",
    modelUrl: ""
  },
  {
    id: "elfbar-raya-d1-blueberry",
    brand: "ELFBAR",
    series: "Raya D1",
    category: "elfbar-raya-d1",
    mainCategory: "disposable",
    flavor: "Blueberry",
    type: "Disposable Pod Device",
    puffs: 13000,
    nicotine: "50mg/ml",
    features: "E-Liquid Display | Power Display | Sunit Edition",
    price: 1199,
    originalPrice: null,
    soldOut: false,
    isBestSelling: true,
    poster: "/images/products/elfbar-raya-d1/blueberry.png",
    cardImage: "/images/products/elfbar-raya-d1/blueberry.png",
    modelUrl: ""
  },
  {
    id: "elfbar-raya-d1-cola",
    brand: "ELFBAR",
    series: "Raya D1",
    category: "elfbar-raya-d1",
    mainCategory: "disposable",
    flavor: "Cola",
    type: "Disposable Pod Device",
    puffs: 13000,
    nicotine: "50mg/ml",
    features: "E-Liquid Display | Power Display | Sunit Edition",
    price: 1199,
    originalPrice: null,
    soldOut: false,
    isBestSelling: false,
    poster: "/images/products/elfbar-raya-d1/cola.png",
    cardImage: "/images/products/elfbar-raya-d1/cola.png",
    modelUrl: ""
  },
  {
    id: "elfbar-raya-d1-blueberry-mint",
    brand: "ELFBAR",
    series: "Raya D1",
    category: "elfbar-raya-d1",
    mainCategory: "disposable",
    flavor: "Blueberry Mint",
    type: "Disposable Pod Device",
    puffs: 13000,
    nicotine: "50mg/ml",
    features: "E-Liquid Display | Power Display | Sunit Edition",
    price: 1199,
    originalPrice: null,
    soldOut: false,
    isBestSelling: true,
    poster: "/images/products/elfbar-raya-d1/blueberry-mint.png",
    cardImage: "/images/products/elfbar-raya-d1/blueberry-mint.png",
    modelUrl: ""
  },
  {
    id: "elfbar-raya-d1-apple-orange-bubblegum",
    brand: "ELFBAR",
    series: "Raya D1",
    category: "elfbar-raya-d1",
    mainCategory: "disposable",
    flavor: "Apple Orange Bubblegum",
    type: "Disposable Pod Device",
    puffs: 13000,
    nicotine: "50mg/ml",
    features: "E-Liquid Display | Power Display | Sunit Edition",
    price: 1199,
    originalPrice: null,
    soldOut: false,
    isBestSelling: false,
    poster: "/images/products/elfbar-raya-d1/apple-orange-bubblegum.png",
    cardImage: "/images/products/elfbar-raya-d1/apple-orange-bubblegum.png",
    modelUrl: ""
  },
  {
    id: "elfbar-raya-d1-cherry-watermelon",
    brand: "ELFBAR",
    series: "Raya D1",
    category: "elfbar-raya-d1",
    mainCategory: "disposable",
    flavor: "Cherry Watermelon",
    type: "Disposable Pod Device",
    puffs: 15000,
    nicotine: "50mg/ml",
    features: "E-Liquid Display | Power Display | Rechargeable | Mint Edition",
    price: 1199,
    originalPrice: null,
    soldOut: false,
    isBestSelling: false,
    poster: "/images/products/elfbar-raya-d1/cherry-watermelon.png",
    cardImage: "/images/products/elfbar-raya-d1/cherry-watermelon.png",
    modelUrl: ""
  },
  {
    id: "elfbar-raya-d1-blue-razz-ice",
    brand: "ELFBAR",
    series: "Raya D1",
    category: "elfbar-raya-d1",
    mainCategory: "disposable",
    flavor: "Blue Razz Ice",
    type: "Disposable Pod Device",
    puffs: 13000,
    nicotine: "50mg/ml",
    features: "E-Liquid Display | Power Display | Sunit Edition",
    price: 1199,
    originalPrice: null,
    soldOut: false,
    isBestSelling: false,
    poster: "/images/products/elfbar-raya-d1/blue-razz-ice.png",
    cardImage: "/images/products/elfbar-raya-d1/blue-razz-ice.png",
    modelUrl: ""
  },
  {
    id: "elfbar-raya-d1-peach-mango",
    brand: "ELFBAR",
    series: "Raya D1",
    category: "elfbar-raya-d1",
    mainCategory: "disposable",
    flavor: "Peach Mango",
    type: "Disposable Pod Device",
    puffs: 13000,
    nicotine: "50mg/ml",
    features: "E-Liquid Display | Power Display | Sunit Edition",
    price: 1199,
    originalPrice: null,
    soldOut: false,
    isBestSelling: false,
    poster: "/images/products/elfbar-raya-d1/peach-mango.png",
    cardImage: "/images/products/elfbar-raya-d1/peach-mango.png",
    modelUrl: ""
  },
  {
    id: "elfbar-raya-d1-mango-strawberry-ice-cream",
    brand: "ELFBAR",
    series: "Raya D1",
    category: "elfbar-raya-d1",
    mainCategory: "disposable",
    flavor: "Mango Strawberry Ice Cream",
    type: "Disposable Pod Device",
    puffs: 13000,
    nicotine: "50mg/ml",
    features: "E-Liquid Display | Power Display | Limited Edition",
    price: 1199,
    originalPrice: null,
    soldOut: false,
    isBestSelling: false,
    poster: "/images/products/elfbar-raya-d1/mango-strawberry-ice-cream.png",
    cardImage: "/images/products/elfbar-raya-d1/mango-strawberry-ice-cream.png",
    modelUrl: ""
  },
  {
    id: "elfbar-raya-d1-double-mango",
    brand: "ELFBAR",
    series: "Raya D1",
    category: "elfbar-raya-d1",
    mainCategory: "disposable",
    flavor: "Double Mango",
    type: "Disposable Pod Device",
    puffs: 13000,
    nicotine: "50mg/ml",
    features: "E-Liquid Display | Power Display | Sunit Edition",
    price: 1199,
    originalPrice: null,
    soldOut: false,
    isBestSelling: false,
    poster: "/images/products/elfbar-raya-d1/double-mango.png",
    cardImage: "/images/products/elfbar-raya-d1/double-mango.png",
    modelUrl: ""
  },

  // ========== ELFBAR Ice King Series ==========
  ...Array(13).fill(null).map((_, i) => ({
    id: `elfbar-ice-king-${['double-mango', 'blue-razz-ice', 'strawberry-kiwi-ice', 'passion-fruit-mango-ice', 'watermelon-bubblegum', 'kiwi-passion-guava', 'ribena-lychee', 'mixed-berry', 'blueberry-ice', 'blackberry-cranberry', 'blueberry-raspberry-watermelon', 'strawberry-watermelon', 'grape-ice'][i]}`,
    brand: "ELFBAR",
    series: "Ice King",
    category: "elfbar-ice-king",
    mainCategory: "disposable",
    flavor: ['Double Mango', 'Blue Razz Ice', 'Strawberry Kiwi Ice', 'Passion Fruit Mango Ice', 'Watermelon Bubblegum', 'Kiwi Passion Fruit Guava', 'Ribena Lychee', 'Mixed Berry', 'Blueberry Ice', 'Blackberry Cranberry', 'Blueberry Raspberry Watermelon', 'Strawberry Watermelon', 'Grape Ice'][i],
    type: "Rechargeable Disposable",
    puffs: 30000,
    nicotine: "5%",
    features: "5-Level Personalized Coolness",
    price: 1699,
    originalPrice: null,
    soldOut: false,
    isBestSelling: i === 0 || i === 2 || i === 11,
    poster: `/images/products/elfbar-ice-king/${['double-mango', 'blue-razz-ice', 'strawberry-kiwi-ice', 'passion-fruit-mango-ice', 'watermelon-bubblegum', 'kiwi-passion-guava', 'ribena-lychee', 'mixed-berry', 'blueberry-ice', 'blackberry-cranberry', 'blueberry-raspberry-watermelon', 'strawberry-watermelon', 'grape-ice'][i]}.png`,
    cardImage: `/images/products/elfbar-ice-king/${['double-mango', 'blue-razz-ice', 'strawberry-kiwi-ice', 'passion-fruit-mango-ice', 'watermelon-bubblegum', 'kiwi-passion-guava', 'ribena-lychee', 'mixed-berry', 'blueberry-ice', 'blackberry-cranberry', 'blueberry-raspberry-watermelon', 'strawberry-watermelon', 'grape-ice'][i]}.png`,
    modelUrl: ""
  })),

  // ========== ELFBAR LOWIT 12000 Series ==========
  ...Array(4).fill(null).map((_, i) => ({
    id: `elfbar-lowit-12000-${['guava-mango', 'watermelon-mango', 'watermelon-lychee', 'strawberry-lychee'][i]}`,
    brand: "ELFBAR",
    series: "LOWIT 12000",
    category: "elfbar-lowit-12000",
    mainCategory: "disposable",
    flavor: ['Guava Mango', 'Watermelon Mango', 'Watermelon Lychee', 'Strawberry Lychee'][i],
    type: "Prefilled Pod",
    puffs: 12000,
    nicotine: "5%",
    features: "Powerful Dual Mesh",
    price: 1199,
    originalPrice: null,
    soldOut: false,
    isBestSelling: i === 0,
    poster: `/images/products/elfbar-lowit-12000/${['guava-mango', 'watermelon-mango', 'watermelon-lychee', 'strawberry-lychee'][i]}.png`,
    cardImage: `/images/products/elfbar-lowit-12000/${['guava-mango', 'watermelon-mango', 'watermelon-lychee', 'strawberry-lychee'][i]}.png`,
    modelUrl: ""
  })),

  // ========== ELFBAR BC20000 Series ==========
  {
    id: "elfbar-bc20000-grape-ice",
    brand: "ELFBAR",
    series: "BC20000",
    category: "elfbar-bc20000",
    mainCategory: "disposable",
    flavor: "Grape Ice",
    type: "Disposable Pod Device",
    puffs: 20000,
    nicotine: "5%",
    features: "Mesh Coil | 15W/35W",
    price: 1299,
    originalPrice: null,
    soldOut: false,
    isBestSelling: true,
    poster: "/images/products/elfbar-bc20000/grape-ice.png",
    cardImage: "/images/products/elfbar-bc20000/grape-ice.png",
    modelUrl: ""
  },
  {
    id: "elfbar-bc20000-mango-twist",
    brand: "ELFBAR",
    series: "BC20000",
    category: "elfbar-bc20000",
    mainCategory: "disposable",
    flavor: "Mango Twist",
    type: "Disposable Pod Device",
    puffs: 20000,
    nicotine: "5%",
    features: "Mesh Coil | 15W/35W",
    price: 1299,
    originalPrice: null,
    soldOut: false,
    isBestSelling: false,
    poster: "/images/products/elfbar-bc20000/mango-twist.png",
    cardImage: "/images/products/elfbar-bc20000/mango-twist.png",
    modelUrl: ""
  },

  // ========== YUOTO Thanos Series ==========
  ...Array(6).fill(null).map((_, i) => ({
    id: `yuoto-thanos-${['double-apple', 'watermelon-ice', 'antonovka-apple', 'passion-fruit', 'orange-juice', 'energy-drink-ice'][i]}`,
    brand: "YUOTO",
    series: "Thanos",
    category: "yuoto-thanos",
    mainCategory: "disposable",
    flavor: ['Double Apple', 'Watermelon Ice', 'Antonovka Apple', 'Passion Fruit', 'Orange Juice', 'Energy Drink Ice'][i],
    type: "Disposable",
    puffs: 5000,
    nicotine: "5%",
    features: null,
    price: 799,
    originalPrice: null,
    soldOut: false,
    isBestSelling: i === 0,
    poster: `/images/products/yuoto-thanos/${['double-apple', 'watermelon-ice', 'antonovka-apple', 'passion-fruit', 'orange-juice', 'energy-drink-ice'][i]}.png`,
    cardImage: `/images/products/yuoto-thanos/${['double-apple', 'watermelon-ice', 'antonovka-apple', 'passion-fruit', 'orange-juice', 'energy-drink-ice'][i]}.png`,
    modelUrl: ""
  })),

  // ========== IGET Disposable Series ==========
  ...Array(11).fill(null).map((_, i) => ({
    id: `iget-disposable-${['strawberry-ice', 'grape-berry', 'cranberry-raspberry-ice', 'cranberry-cherry-ice', 'strawberry-lemon', 'mountain-spring-ice', 'strawberry-watermelon-kiwi', 'blackberry-ice', 'blueberry-mint', 'watermelon-ice', 'cranberry-lemon'][i]}`,
    brand: "IGET",
    series: "Disposable",
    category: "iget-disposable",
    mainCategory: "disposable",
    flavor: ['Strawberry Ice', 'Grape Berry', 'Cranberry Raspberry Ice', 'Cranberry Cherry Ice', 'Strawberry Lemon', 'Mountain Spring Ice', 'Strawberry Watermelon Kiwi', 'Blackberry Ice', 'Blueberry Mint', 'Watermelon Ice', 'Cranberry Lemon'][i],
    type: "Disposable Pod Device",
    puffs: 10000,
    nicotine: "5%",
    features: null,
    price: 999,
    originalPrice: null,
    soldOut: false,
    isBestSelling: i === 1 || i === 9,
    poster: `/images/products/iget-disposable/${['strawberry-ice', 'grape-berry', 'cranberry-raspberry-ice', 'cranberry-cherry-ice', 'strawberry-lemon', 'mountain-spring-ice', 'strawberry-watermelon-kiwi', 'blackberry-ice', 'blueberry-mint', 'watermelon-ice', 'cranberry-lemon'][i]}.png`,
    cardImage: `/images/products/iget-disposable/${['strawberry-ice', 'grape-berry', 'cranberry-raspberry-ice', 'cranberry-cherry-ice', 'strawberry-lemon', 'mountain-spring-ice', 'strawberry-watermelon-kiwi', 'blackberry-ice', 'blueberry-mint', 'watermelon-ice', 'cranberry-lemon'][i]}.png`,
    modelUrl: ""
  })),

  // ========== IGET FLAME B10000 Series ==========
  ...Array(8).fill(null).map((_, i) => ({
    id: `iget-flame-b10000-${['mountain-spring-mint', 'grape-berry', 'strawberry-watermelon-kiwi', 'blackberry-ice', 'strawberry-lemon', 'blueberry-mint', 'cranberry-raspberry-ice', 'watermelon-ice'][i]}`,
    brand: "IGET",
    series: "FLAME B10000",
    category: "iget-flame-b10000",
    mainCategory: "disposable",
    flavor: ['Mountain Spring Mint', 'Grape Berry', 'Strawberry Watermelon Kiwi', 'Blackberry Ice', 'Strawberry Lemon', 'Blueberry Mint', 'Cranberry Raspberry Ice', 'Watermelon Ice'][i],
    type: "Disposable Pod Device",
    puffs: 10000,
    nicotine: "5%",
    features: null,
    price: 1099,
    originalPrice: null,
    soldOut: false,
    isBestSelling: i === 1,
    poster: `/images/products/iget-flame-b10000/${['mountain-spring-mint', 'grape-berry', 'strawberry-watermelon-kiwi', 'blackberry-ice', 'strawberry-lemon', 'blueberry-mint', 'cranberry-raspberry-ice', 'watermelon-ice'][i]}.png`,
    cardImage: `/images/products/iget-flame-b10000/${['mountain-spring-mint', 'grape-berry', 'strawberry-watermelon-kiwi', 'blackberry-ice', 'strawberry-lemon', 'blueberry-mint', 'cranberry-raspberry-ice', 'watermelon-ice'][i]}.png`,
    modelUrl: ""
  })),

  // ========== ELFWORLD MX25000 Series ==========
  {
    id: "elfworld-mx25000-peach-blue-slushy",
    brand: "ELFWORLD",
    series: "MX25000",
    category: "elfworld-mx25000",
    mainCategory: "disposable",
    flavor: "Peach Blue Slushy",
    type: "Disposable",
    puffs: 25000,
    nicotine: "5%",
    features: "Dual Mesh Coil | 25000 Puffs",
    price: 1599,
    originalPrice: null,
    soldOut: false,
    isBestSelling: false,
    poster: "/images/products/elfworld-mx25000/peach-blue-slushy.png",
    cardImage: "/images/products/elfworld-mx25000/peach-blue-slushy.png",
    modelUrl: ""
  },
  {
    id: "elfworld-mx25000-strawberry-ice",
    brand: "ELFWORLD",
    series: "MX25000",
    category: "elfworld-mx25000",
    mainCategory: "disposable",
    flavor: "Strawberry Ice",
    type: "Disposable",
    puffs: 25000,
    nicotine: "5%",
    features: "Dual Mesh Coil | 25000 Puffs",
    price: 1599,
    originalPrice: null,
    soldOut: false,
    isBestSelling: false,
    poster: "/images/products/elfworld-mx25000/strawberry-ice.png",
    cardImage: "/images/products/elfworld-mx25000/strawberry-ice.png",
    modelUrl: ""
  },
  {
    id: "elfworld-mx25000-raspberry-peach-lime",
    brand: "ELFWORLD",
    series: "MX25000",
    category: "elfworld-mx25000",
    mainCategory: "disposable",
    flavor: "Raspberry Peach Lime",
    type: "Disposable",
    puffs: 25000,
    nicotine: "5%",
    features: "Dual Mesh Coil | 25000 Puffs",
    price: 1599,
    originalPrice: null,
    soldOut: false,
    isBestSelling: false,
    poster: "/images/products/elfworld-mx25000/raspberry-peach-lime.png",
    cardImage: "/images/products/elfworld-mx25000/raspberry-peach-lime.png",
    modelUrl: ""
  },
  {
    id: "elfworld-mx25000-pink-lemonade",
    brand: "ELFWORLD",
    series: "MX25000",
    category: "elfworld-mx25000",
    mainCategory: "disposable",
    flavor: "Pink Lemonade",
    type: "Disposable",
    puffs: 25000,
    nicotine: "5%",
    features: "Dual Mesh Coil | 25000 Puffs",
    price: 1599,
    originalPrice: null,
    soldOut: false,
    isBestSelling: false,
    poster: "/images/products/elfworld-mx25000/pink-lemonade.png",
    cardImage: "/images/products/elfworld-mx25000/pink-lemonade.png",
    modelUrl: ""
  },
  {
    id: "elfworld-mx25000-juicy-peach-ice",
    brand: "ELFWORLD",
    series: "MX25000",
    category: "elfworld-mx25000",
    mainCategory: "disposable",
    flavor: "Juicy Peach Ice",
    type: "Disposable",
    puffs: 25000,
    nicotine: "5%",
    features: "Dual Mesh Coil | 25000 Puffs",
    price: 1599,
    originalPrice: null,
    soldOut: false,
    isBestSelling: false,
    poster: "/images/products/elfworld-mx25000/juicy-peach-ice.png",
    cardImage: "/images/products/elfworld-mx25000/juicy-peach-ice.png",
    modelUrl: ""
  },
  {
    id: "elfworld-mx25000-grape-ice",
    brand: "ELFWORLD",
    series: "MX25000",
    category: "elfworld-mx25000",
    mainCategory: "disposable",
    flavor: "Grape Ice",
    type: "Disposable",
    puffs: 25000,
    nicotine: "5%",
    features: "Dual Mesh Coil | 25000 Puffs",
    price: 1599,
    originalPrice: null,
    soldOut: false,
    isBestSelling: true,
    poster: "/images/products/elfworld-mx25000/grape-ice.png",
    cardImage: "/images/products/elfworld-mx25000/grape-ice.png",
    modelUrl: ""
  },

  // ========== UWELL / CALIBURN Series (PODKITS) ==========
  {
    id: "uwell-caliburn-g4-pro-koko",
    brand: "UWELL",
    series: "Caliburn G4 Pro KOKO",
    category: "uwell-caliburn",
    mainCategory: "podkits",
    flavor: null,
    type: "Pod System",
    puffs: null,
    nicotine: "Variable",
    features: "2000 mAh | 2.0 Inch Touch | G Pod Platform",
    price: 3499,
    originalPrice: null,
    soldOut: false,
    isBestSelling: true,
    poster: "/images/products/uwell-caliburn/g4-pro-koko.png",
    cardImage: "/images/products/uwell-caliburn/g4-pro-koko.png",
    modelUrl: ""
  },
  {
    id: "uwell-caliburn-g4-pro",
    brand: "UWELL",
    series: "Caliburn G4 Pro",
    category: "uwell-caliburn",
    mainCategory: "podkits",
    flavor: null,
    type: "Pod System",
    puffs: null,
    nicotine: "Variable",
    features: "1800 mAh | Touch Control",
    price: 3299,
    originalPrice: null,
    soldOut: false,
    isBestSelling: false,
    poster: "/images/products/uwell-caliburn/g4-pro.png",
    cardImage: "/images/products/uwell-caliburn/g4-pro.png",
    modelUrl: ""
  }
]

// Main navigation categories (matching the reference navigation)
export const MAIN_CATEGORIES = {
  'all': 'All Products',
  'podkits': 'PODKITS',
  'most-selling': 'MOST SELLING',
  'shop-by-brands': 'SHOP BY BRANDS',
  'shop-by-price': 'SHOP BY PRICE',
  'disposable': 'DISPOSABLE',
  'nic-salts': 'NICSALTS',
  'shop-by-puffs': 'SHOP BY PUFFS',
  'pods-coils': 'PODS & COILS'
}

// Brands for SHOP BY BRANDS filter (extracted from actual product data)
// ELFBAR has multiple series: Moonlight 40K, Sweet King, Raya D3, Raya D1, Ice King, LOWIT 12000, BC20000
// IGET has: Disposable, FLAME B10000
// YUOTO has: Thanos
// ELFWORLD has: MX25000
// UWELL has: Caliburn G4 Pro, Caliburn G4 Pro KOKO
export const BRANDS = [
  'ELFBAR',
  'YUOTO', 
  'IGET',
  'ELFWORLD',
  'UWELL'
]

// Price ranges for SHOP BY PRICE filter (based on actual product prices: 799, 999, 1099, 1199, 1299, 1399, 1599, 1699, 1799, 3299, 3499)
export const PRICE_RANGES = [
  { id: '0-1000', label: '₹0 - ₹1,000', min: 0, max: 1000 },
  { id: '1000-1500', label: '₹1,000 - ₹1,500', min: 1000, max: 1500 },
  { id: '1500-2000', label: '₹1,500 - ₹2,000', min: 1500, max: 2000 },
  { id: '2000-3000', label: '₹2,000 - ₹3,000', min: 2000, max: 3000 },
  { id: '3000+', label: '₹3,000+', min: 3000, max: Infinity }
]

// Puff ranges for SHOP BY PUFFS filter (based on actual product puffs: 5000, 10000, 12000, 15000, 20000, 25000, 30000, 40000)
// Ranges are inclusive on both ends for better user experience
export const PUFF_RANGES = [
  { id: '0-5000', label: 'Up to 5,000 Puffs', min: 0, max: 5000 },
  { id: '5000-10000', label: '5,000 - 10,000 Puffs', min: 5000, max: 10000 },
  { id: '10000-20000', label: '10,000 - 20,000 Puffs', min: 10000, max: 20000 },
  { id: '20000-30000', label: '20,000 - 30,000 Puffs', min: 20000, max: 30000 },
  { id: '30000+', label: '30,000+ Puffs', min: 30000, max: Infinity }
]

// Helper function to get sub-categories (series) for a specific brand
export const getSubCategoriesByBrand = (brand) => {
  if (!brand) return []
  const brandProducts = PRODUCTS.filter(p => p.brand === brand)
  const uniqueSeries = [...new Set(brandProducts.map(p => p.series).filter(Boolean))]
  return uniqueSeries.sort()
}

// Legacy category mapping for backward compatibility
export const CATEGORIES = MAIN_CATEGORIES